### ISSUE TITLE
The get command doesn't support multiple sources

### ISSUE THREAD

**Issue by imoverclocked** [colinmarc/hdfs#57] opened 2016-11-04 05:31 UTC
`hdfs ls /path/to/file*` and `hdfs get /path/to/file* /local/dir/` would be amazing.

**Comment by colinmarc** [comment] 2016-11-04 09:19
That should work - including the tab complete! if not it's a bug.

**Comment by imoverclocked** [comment] 2016-11-06 06:00
Looks like ls works but get does not.

```
$ hdfs mkdir /test
$ hdfs touch /test/1
$ hdfs touch /test/2
$ hdfs touch /test/3
$ hdfs get /test/\* test/
stat /test/*: file does not exist
```

**Comment by colinmarc** [comment] 2016-12-06 01:03
Hm - that was intended at the time, but it does look like it diverges from the `hadoop fs` behavior. Thanks for the report!

**Comment by nlevitt** [comment] 2017-04-10 22:51
`hdfs ls /nonexistent*` gives me a listing of my hdfs user dir (in other words, it acts like `hdfs ls` with no args)

**Comment by colinmarc** [comment] 2018-08-07 14:00
Whoops, didn't intend to close this. https://github.com/colinmarc/hdfs/commit/c5e93df697d823976844a79ec9a70e51105b4639 Only fixes `ls /nonexistent*`.

**Comment by colinmarc** [comment] 2018-08-07 14:11
So, I did some poking at how this works. The `hadoop fs` behavior is super obnoxious. `hadoop fs` allows this:

```
$ hadoop fs -get
Usage: hadoop fs [generic options] -get [-p] [-ignoreCrc] [-crc] <src> ... <localdst>
$ hadoop fs -get /_test/*.txt
```
But if I expand the glob myself, it doesn't work:

```
$ hadoop fs -get /_test/foo.txt /_test/mobydick.txt
get: `/_test/mobydick.txt': No such file or directory
```

In this case, `localdst` is optional, and it resolves the ambiguity (is the second text file the destination or another source?) by interpreting my glob as only a single argument.

I'm not willing to do that for this library, because it is confusing in a posix context where globs are expanded before being passed to the program. So the options are to only allow a single source, like I do now, or require dest. But if I require dest, then `get *.txt` suddenly starts failing with a confusing error message.

I'm going to keep this as-written, but feel free to pipe in if you think I'm wrong.

**Closed by colinmarc** 2018-08-07 14:11 UTC
Labels: good first issue
