### ISSUE TITLE
HDFS data transfer encryption support

### ISSUE THREAD

**Issue by mxk1235** [colinmarc/hdfs#145] opened 2018-09-11 18:01 UTC
I was attempting to use this library against an hdfs cluster that has `hadoop.rpc.protection` setting in core-site.xml set to `privacy`, as well as  `dfs.encrypt.data.transfer` which is `true` in hdfs-site.xml.   i believe those apply to the protobuf rpc interface.  

the error message i received was the following. 
```no available namenodes: SASL handshake: wrong Token ID. Expected 0504, was 6030  ```

after some debugging i think it occurs here https://github.com/colinmarc/hdfs/blob/master/internal/rpc/kerberos.go#L67 . i suspect the namenode is replying with an encrypted message, while the doKerberosHandshake() expects otherwise.

on first look the library just sets the default value for  `dfs.encrypt.data.transfer`  property as `false`
https://github.com/colinmarc/hdfs/blob/f87e1d64bc48c85b07cab32d23c97788e885b31b/internal/protocol/hadoop_hdfs/hdfs.proto#L402
 and there is no way of creating a client with that property set to true. 
https://github.com/colinmarc/hdfs/blob/f87e1d64bc48c85b07cab32d23c97788e885b31b/client.go#L122

there is a fetchDefaults() function, that's only invoked by file_writer, but not by file_reader (e.g. Stat(), Readdir(), and Read() methods).

can you comment if i'm digging in the right place, and whether the encrypted part of the protocol applies to the read functionality?

here are relevant properties from core-site.xml

```
  <property>
    <name>hadoop.security.authentication</name>
    <value>kerberos</value>
  </property>
  <property>
    <name>hadoop.security.authorization</name>
    <value>true</value>
  </property>
  <property>
    <name>hadoop.rpc.protection</name>
    <value>privacy</value>
  </property>
```

and hdfs-site.xml

```
  <property>
    <name>dfs.encrypt.data.transfer.algorithm</name>
    <value>3des</value>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.suites</name>
    <value>AES/CTR/NoPadding</value>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.key.bitlength</name>
    <value>256</value>
  </property>
  <property>
    <name>dfs.namenode.acls.enabled</name>
    <value>true</value>
  </property>
```

**Comment by colinmarc** [comment] 2018-09-12 08:31
Hi there,

Thanks for the report!

This looks like an accurate assessment of the missing functionality. I don't know how it works, but I'll try to do some research.

**Comment by mnotti** [comment] 2018-09-25 22:19
Getting very similar issue at the same spot during the doKerberosHandshake():
`Couldn't connect to namenode: no available namenodes: SASL handshake: wrong Token ID. Expected 0504, was 603f` 

However, I have either `hadoop.rpc.protection` setting in core-site.xml, or `dfs.encrypt.data.transfer` in hdfs-site.xml like mxk12345 above. 

Unsure what to look for here. I get the same issue using the binary provided as well as the lib api itself.

**Comment by colinmarc** [comment] 2018-09-26 08:58
@Shastick do you have any idea on this?

**Comment by Shastick** [comment] 2018-09-26 17:57
Sorry for the delay. @mxk1235 you are digging in the correct place. However, we did not implement the "privacy" mode of operation (as well as any other work that relies on Kerberos to sign or encrypt payloads) when integrating gokrb5 into the client. This is mainly because we did not need it, and the additional work was non-trivial.

If you are interested in attempting to implement this, the RFC's mentionned in the source code (possible the one of gokrb5, I'm not sure anymore) will contain the relevant pointers.

Hope this helps

**Comment by mxk1235** [comment] 2018-09-26 18:57
@Shastick i kept looking and i think the error occurs at this line

https://github.com/colinmarc/hdfs/blob/f87e1d64bc48c85b07cab32d23c97788e885b31b/internal/rpc/kerberos.go#L67

which i think is past communication with the KDC and rather talking to the namenode.  every time i look i get a little deeper, but obviously this is a lot to implement.

**Comment by colinmarc** [comment] 2018-09-26 20:19
@shastick thanks. I know you've given a lot of your time already, but it would be immensely helpful if you could create issues for any missing kerberos things you can think of. I didn't even know wire encryption was a thing.

**Comment by Shastick** [comment] 2018-09-27 02:49
@mxk1235 the line you are referring to corresponds to the deserialisation (and verification) of the token that was sent back by the namenode. If this token is anything else than a signed wrap token (e.g, a sealed wrap token) then it blows up at this point.

@colinmarc I'll peruse https://tools.ietf.org/html/rfc4121 a bit when I get some time and will try to remember what other modes we skipped over

**Comment by freshsun** [comment] 2018-11-28 07:41
I get the same error today. _"no available namenodes: SASL handshake: wrong Token ID. Expected 0504, was 6030"_ 
I have no _hadoop.rpc.protection_ and _dfs.encrypt.data.transfer_ settings on the server.
I also tried native java hadoop client to list the files, I can see the command and return file list in the tcp bodies, so i guess it's not encrypted?
Packages from go hdfs and java hdfs command are different, java version has more packages before the package contains hex 6030 show up.

**Comment by colinmarc** [comment] 2018-11-29 19:14
@freshsun that's really useful information. Can you post a hexdump of the packet with 0504, or email it to hi@colinmarc.com if you're not comfortable posting it?

**Comment by freshsun** [comment] 2018-12-04 01:43
@mnotti check my workaround solution https://github.com/colinmarc/hdfs/issues/144#issuecomment-443937512

**Comment by jackyliang** [comment] 2018-12-18 22:22
My name is Jacky and I am a product manager at MemSQL (colleague of @mxk1235)

I would like to 👍 on implementing support for RPC authentication + HDFS wire encryption for this library -- it will solve a major need for our customers that run Hadoop clusters but want to ingest data into MemSQL in a secure fashion. 

My colleague's note are an accurate reflection on one of the things that this awesome library doesn't yet support (`hadoop.rpc.protection` set to `privacy` which enables RPC authentication, `hdfs.encrypt.data.transfer` set to `true` for HDFS encrypted data transfer)

**Comment by colinmarc** [comment] 2018-12-19 09:19
Hi Jacky,

Thanks for the feedback. I don't really have the time or test environment to do further work on the krb stuff, but I'd obviously  welcome contributions.

**Comment by jaguarx** [comment] 2019-05-06 04:14
Hi,
  Just echo the cause, as I just ran into similar setup here.
  I believe the the package should be *unwrapped* (wrap/unwrap in GSSAPI/SASL terms), before feeding to protobuf for deserialization.
  Looks like some refactoring need to be done in rpc module. Any ideas?

Best!
Jaguar

**Comment by colinmarc** [comment] 2020-07-17 08:00
Closed in 1596ee1307eb423a2ed092713f1368157d67ce86, thanks to @zeroshade!

**Closed** 2020-07-17 08:00 UTC

**Comment by colinmarc** [comment] 2020-07-17 15:21
@jackyliang, @mxk1235 - would you be willing to test 1596ee1307eb423a2ed092713f1368157d67ce86 in your environment before I cut a release? Thanks in advance.

**Comment by mxk1235** [comment] 2020-07-18 17:18
@colinmarc yes I could test it sometime next week.
