### ISSUE TITLE
write tcp 192.168.89.110:54820->192.168.89.112:50010: write: broken pipe

### ISSUE THREAD

**Issue by JKeita** [colinmarc/hdfs#172] opened 2019-02-28 08:07 UTC
```
package main

import (
	"fmt"
	"github.com/colinmarc/hdfs"
	"time"
)

func main() {
	url := "centos1:9000"
	var err error
	var client *hdfs.Client
	if client, err = hdfs.New(url); err != nil {
		fmt.Println(err)
		return
	}
	fileName := "/data/test/1.log"
	var writer *hdfs.FileWriter
	writer, err = client.Create(fileName)
	if err != nil {
		fmt.Println(err)
		return
	}
	_, err = writer.Write([]byte("test1"))
	if err != nil {
		fmt.Println("test 1 write err:", err)
	}
	time.Sleep(2 * time.Minute)
	_, err = writer.Write([]byte("test2"))
	if err != nil {
		fmt.Println("test 2 write err:", err)
	}
	err = writer.Close()
	if err != nil {
		fmt.Println("close err:", err)
	}
}
```
output:
[root@centos1 test]# go run test.go 
close err: write tcp 192.168.89.110:60194->192.168.89.112:50010: write: broken pipe

**Comment by colinmarc** [comment] 2019-02-28 16:48
Pretty sure this is a duplicate of #60. Sorry that the error is so opaque.

**Closed by colinmarc** 2019-02-28 16:48 UTC
