### ISSUE TITLE
connection reset by peer error when trying to put and get files using hdfs binary

### ISSUE THREAD

**Issue by cristianodarocha** [colinmarc/hdfs#248] opened 2020-09-29 14:13 UTC
I'm currently running a CDH 5.16.2 Kerberized cluster and I've been trying to use the hdfs binary. Apparently, it is related to an issue when trying to connect to the data nodes

**It works fine for listing files**

`$ ./hdfs ls /user/my_user/`

**It doesn't work for getting/downloading files**

`$ ./hdfs get /user/my_user/test_file.conf
read tcp <IP_SOURCE>:52690-><IP_DESTINATION>:50010: read: connection reset by peer`

**It doesn't work for putting/uploading files**

`$ ./hdfs put /home/my_user/test_file.conf /user/my_user/test_file.conf
read tcp <IP_SOURCE>:52690-><IP_DESTINATION>:50010: read: connection reset by peer`

**Comment by colinmarc** [comment] 2020-12-30 11:03
Closing as a duplicate of #258.

**Closed by colinmarc** 2020-12-30 11:03 UTC
