### ISSUE TITLE
Reading in blocks does not return error on partial fail

### ISSUE THREAD

**Issue by weirichpaola** [colinmarc/hdfs#96] opened 2018-01-15 16:59 UTC
On "block_reader.go" when block is partially read error is returned as nil and ignored (line 83).
Error should be returned in order of further treatments. It is also returned as nil on "file_reader.go"

**Comment by colinmarc** [comment] 2018-01-15 17:15
@weirichpaola Hi! That's intended behavior - I think that's correct for the definition of [`io.Reader.Read`](https://godoc.org/io#Reader):

> Read reads up to len(p) bytes into p. It returns the number of bytes read (0 <= n <= len(p)) and any error encountered. Even if Read returns n < len(p), it may use all of p as scratch space during the call. If some data is available but not len(p) bytes, Read conventionally returns what is available instead of waiting for more.

Go gives you tools in `io` for dealing with this: [`io.ReadFull`](https://godoc.org/io#ReadFull) and [`io.CopyN`](https://golang.org/pkg/io/#CopyN), for example.

I'm going to close this, but feel free to reopen if anything I said seems incorrect :)

**Closed by colinmarc** 2018-01-15 17:15 UTC
