### ISSUE TITLE
Write HDFS data Socket time out

### ISSUE THREAD

**Issue by xxh2000** [colinmarc/hdfs#135] opened 2018-07-28 16:06 UTC
When I use the write method to write data, the write will fail after more than 60s. When close the file, the EOF error is reported. The log of the datanode is that The socket has timed out. If the data is written within 60s and close, there is no problem. Over 60s, the socket timeout is reported.

```
2018-07-26 17:29:22,914 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: PacketResponder: BP-43523165-10.201.80.193-1500276327849:blk_1073741853_1040, type=HAS_DOWNSTREAM_IN_PIPELINE
java.io.EOFException: Premature EOF: no length prefix available
    at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2207)
    at org.apache.hadoop.hdfs.protocol.datatransfer.PipelineAck.readFields(PipelineAck.java:176)
    at org.apache.hadoop.hdfs.server.datanode.BlockReceiver$PacketResponder.run(BlockReceiver.java:1165)
    at java.lang.Thread.run(Thread.java:745)
2018-07-26 17:29:22,953 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Exception for BP-43523165-10.201.80.193-1500276327849:blk_1073741853_1040
java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/10.201.80.195:50010 remote=/10.136.16.91:55943]
    at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
    at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
    at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at java.io.DataInputStream.read(DataInputStream.java:149)
    at org.apache.hadoop.io.IOUtils.readFully(IOUtils.java:192)
    at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.doReadFully(PacketReceiver.java:213)
    at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.doRead(PacketReceiver.java:134)
    at org.apache.hadoop.hdfs.protocol.datatransfer.PacketReceiver.receiveNextPacket(PacketReceiver.java:109)
    at org.apache.hadoop.hdfs.server.datanode.BlockReceiver.receivePacket(BlockReceiver.java:467)
    at org.apache.hadoop.hdfs.server.datanode.BlockReceiver.receiveBlock(BlockReceiver.java:781)
    at org.apache.hadoop.hdfs.server.datanode.DataXceiver.writeBlock(DataXceiver.java:761)
    at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.opWriteBlock(Receiver.java:137)
    at org.apache.hadoop.hdfs.protocol.datatransfer.Receiver.processOp(Receiver.java:74)
    at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:237)
    at java.lang.Thread.run(Thread.java:745)
2018-07-26 17:29:22,953 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: PacketResponder: BP-43523165-10.201.80.193-1500276327849:blk_1073741853_1040, type=HAS_DOWNSTREAM_IN_PIPELINE: Thread is interrupted.
2018-07-26 17:29:22,953 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: PacketResponder: BP-43523165-10.201.80.193-1500276327849:blk_1073741853_1040, type=HAS_DOWNSTREAM_IN_PIPELINE terminating
```

**Comment by colinmarc** [comment] 2018-07-30 13:46
I'm pretty sure this is a duplicate of #60. Feel free to reopen if I have that wrong!

**Closed by colinmarc** 2018-07-30 13:46 UTC

**Comment by xxh2000** [comment] 2018-08-01 02:13
After my test, I think this is not a lease issue and lease issues will appear in an hour, but a socket idle timeout.  When the client has no data written to the datanode for more than 60 seconds, the connection will be closed by the datanode. If persistent data is written to hdfs, then this problem does not . here is the test code

```
    client, err := hdfs.New("10.202.80.193:8020")
	if err != nil {
		fmt.Fatal(err)
	}
	fw, err := client.Create("/user/hadoop/testdata.log")
	if err != nil {
		log.Fatalf("create file error,%v",err)
	}
	_, err = fw.Write([]byte("first line hello hello \n"))
	if err != nil {
		log.Fatalf("write data error , %v", err)
	}
	fw.Flush()

	//sleep 70s and it will report EOF exception when close the fw
       // if sleep time is less than 60, there is no issue.
	time.Sleep(time.Duration(70) * time.Second)
	_, err = fw.Write([]byte("the second line...\n"))
	err = fw.Close()
	if err != nil {
		log.Fatalf("close err,%v", err)
	}
```

**Comment by colinmarc** [comment] 2018-08-01 12:49
All the same, the error message indicates to me that renewing the lease would solve this issue as well. The datanode wants to read any op message at all, and when it doesn't after 60s then it closes the connection to the client.

**Comment by JKeita** [comment] 2019-03-01 08:00
@xxh2000  How do you reslove this?
