### ISSUE TITLE
read tcp 10.62.49.37:36500->10.62.49.37:61004: read: connection reset by peer

### ISSUE THREAD

**Issue by liuliu4348** [colinmarc/hdfs#184] opened 2019-05-07 12:52 UTC
I was attempting to use this library to connect to the hdfs cluster which was configured with kerberos. Some setting is blow:
core-site.xml
```
<property>   
        <name>hadoop.security.authentication</name>
        <value>kerberos</value>
 </property>
<property>
        <name>hadoop.security.authorization</name>
        <value>true</value>
</property>
```

hdfs-site.xml
 ```
<property>
      <name>dfs.data.transfer.protection</name>
      <value>integrity</value>
 </property>
```
when I upload or download file from hdfs, it returns "read tcp 10.62.49.37:36500->10.62.49.37:61004: read: connection reset by peer". I suspect this library doesn't support SASL read and write and I find similar issue #145.

**Comment by xtrimf** [comment] 2019-09-22 14:12
I get the same error when writing large files...

**Comment by colinmarc** [comment] 2019-11-24 00:15
Closing as a duplicate of #145.

**Closed by colinmarc** 2019-11-24 00:15 UTC
