### ISSUE TITLE
"stat: /someDir: unexpected sequence number"

### ISSUE THREAD

**Issue by netrc** [colinmarc/hdfs#144] opened 2018-09-07 15:58 UTC
Running hdfs ls  hdfs://namenodeServer.xyz.com:8020/someDir

Returns "stat: /someDir: unexpected sequence number"

[internal/rpc/namenode.go: readResponse()  
](https://github.com/colinmarc/hdfs/blob/master/internal/rpc/namenode.go#L252)
Ever seen this? HDFS version mismatch ?

**Comment by colinmarc** [comment] 2018-09-12 08:31
Huh - never seen that at all. Do you get it all the time or just sometime?

**Comment by netrc** [comment] 2018-09-12 11:40
Every time; immediate return.  I now think it's related to some kerberos mismatch but can't see where. I've got a principal, klist looks good, ticket in /tmp/krb5cc_nnnn.   Hadoop hdfs (jvm) works fine.

**Comment by colinmarc** [comment] 2018-09-13 13:04
@netrc do you have the properties in #145 set? I'm thinking it might be that. Anything else specific about your setup? What distro of hadoop?

**Comment by colinmarc** [comment] 2018-09-26 08:59
@netrc sorry, what do you mean by correctly? Do you have encryption set up or no?

**Comment by xxh2000** [comment] 2018-10-08 02:34
I also encountered this problem, when using the hdfs command to access HDFS that opens kerberos will prompt this error.

**Comment by colinmarc** [comment] 2018-10-08 07:31
@xxh2000 do you mind clarifying exactly what steps I can take to reproduce?

**Comment by zeroshade** [comment] 2018-11-20 21:11
Hi @colinmarc 
So I've been looking into this as I hit the same problem. I'm using Kerberos authentication and hadoop 2.7.3. 

I tried to do a simple `hdfs ls /user/` and got the same "unexpected sequence number" error message. Coming from https://github.com/colinmarc/hdfs/blob/master/internal/rpc/namenode.go#L252 because the return of `int32(rrh.GetCallId())` is -33, the same as the SASL call id used earlier, but `c.currentRequestID` is 1 so it doesn't match. 

I've tried inspecting the actual response body and comparing the code to how other clients that work with this cluster (like libhdfs3) work and I've noticed a couple differences between this library and those.

So looking at the hadoop-common java code and libhdfs3, the value for the AuthMethod for kerberos / GSSAPI is 81 while this library is using 0xDF, where did the 0xDF value come from?

I've also noticed that I think when using kerberos, those libraries create a SaslRpcClient which seems to have all the requests and responses wrapped by sasl, is that something which should be being done here? I'll keep digging but I hope you can help out with this.

**Comment by freshsun** [comment] 2018-11-30 08:30
Got the same problem for properties referenced in #145 enabled. If i removed these properties, client works ok. (not the client in https://github.com/colinmarc/hdfs/issues/145#issuecomment-442349761, which i am still digging on)
Seems that client send the correct getFileInfo request but receive a response it cannot recognize. 
I guess some working sets of hdfs & kdc configs from other users might help to filter out which hadoop version/property is not compatible.

**Comment by zeroshade** [comment] 2018-11-30 17:33
So i looked a bit further into this and toyed around with various solutions and basically figured out the issue is when using kerberos/sasl communication such that the rpc calls are also encrypted. along with the data. I managed to get namenode stat calls (ls and the like) working by storing the `sessionKey` retrieved from the kerberos ticket during `doKerberosHandshake` and then modifying the namenode's `readResponse` method to look like so:

```go
func (c *NamenodeConnection) readResponse(method string, resp proto.Message) error {
    rrh := &hadoop.RpcResponseHeaderProto{}
    var err error
    _, ok := resp.(*hadoop.RpcSaslProto)
    if c.kerberosClient != nil && !ok {
        // if we're using kerberos, and was opening a sasl message, use sasl to decrypt the payload
        sasl := &hadoop.RpcSaslProto{}
        err = readRPCPacket(c.conn, rrh, sasl)
        if err != nil {
            return err
        } else if int32(rrh.GetCallId()) != -33 {
            return errors.New("Kerberos Didn't send Sasl?")
        }
    
        var reqToken gssapi.WrapToken
        err = reqToken.Unmarshal(sasl.GetToken(), true)
        if err != nil {
            return err
        }
        unwrapped, err := crypto.DecryptMessage(reqToken.Payload,
                                                /* the stored sessionKey from the kerberos ticket */,
                                                c.currKey, 
                                                keyusage.GSSAPI_ACCEPTOR_SEAL)
        if err != nil {
            return err
        }
        // read the decrypted actual message and then continue normally
        err = readRPCPacket(bytes.NewReader(unwrapped), rrh, resp)
    } else {
        err = readRPCPacket(c.conn, rrh, resp)
    }
  
    if err != nil {
        return err
    } else if int32(rrh.GetCallId()) != c.currentRequestID {
        return errors.New("unexpected sequence number")
    } else if rrh.GetStatus() != hadoop.RpcResponseHeaderProto_SUCCESS {
        return &NamenodeError{
                     method:    method,
		     message:   rrh.GetErrorMsg(),
		     code:      int(rrh.GetErrorDetail()),
		     exception: rrh.GetExceptionClassName(),
        }
    }
    return nil
}
```

Granted, i'm sure there's a more elegant way to do this, but this worked for my namenode interactions. Unfortunately, I ran into issues getting files to transfer and I'm guessing that it's the same issues mentioned in #145 

Based on looking at the code for other hdfs clients, I think the ideal solution for both this, and #145 would be to create a sasl requester so that the logic to transparently decrypt messages with callid -33 can be centralized and used by both the namenode and datanode interactions, or something along those lines.

**Comment by freshsun** [comment] 2018-12-04 01:41
I got a workaround solution finally.

 id | property | value
--- | --- | ---
1 | hadoop.security.authentication | kerberos 
2 | hadoop.security.authorization | true 
3 | hadoop.rpc.protection | x
4 | dfs.data.transfer.protection | x
5 | dfs.encrypt.data.transfer | x

**NO property with id 3,4,5** should exist in the settings. They control the rpc encryption and data transfer encryption. 
When 4 is enabled with authenticate, file can be list and remove, but not get/put, because property 4 influence communication with datanodes

Another point is Kerberos encrypt method should be set with **aes256-cts-hmac-sha1-96**(maybe other but I haven't tested) and definitely **NOT rc4-hmac**. (not as gokrb5 suggested...)
Kerberos itself has made aes256-cts-hmac-sha1-96 default with highest priority. But CDH5 use rc4-hmac as default, it needs to be paid attention on. 

I have a working environment with all these settings on CDH5.

**Comment by dtaniwaki** [comment] 2019-02-19 14:20
I implemented the SASL handler for protected RPC messages.
https://github.com/colinmarc/hdfs/pull/170

I think it solves this issue while it doesn't solve `dfs.data.transfer.protection` issue reported in #145.

**Comment by Ostaer** [comment] 2019-03-07 12:33
@zeroshade what is c.currKy ?

> ```go
>   unwrapped, err := crypto.DecryptMessage(reqToken.Payload,
>                                                 /* the stored sessionKey from the kerberos ticket */,
>                                                 c.currKey, 
>                                                 keyusage.GSSAPI_ACCEPTOR_SEAL)
> ```

**Comment by kangyanf2008** [comment] 2019-04-28 11:38
Is there a solution?  func (c *NamenodeConnection) readResponse(method string, resp proto.Message) error {
	rrh := &hadoop.RpcResponseHeaderProto{}
	err := readRPCPacket(c.conn, rrh, resp)
	if err != nil {
		return err
	} else if **_int32(rrh.GetCallId()) != c.currentRequestID_** {
		return errors.New("unexpected sequence number")
	} else if rrh.GetStatus() != hadoop.RpcResponseHeaderProto_SUCCESS {
		return &NamenodeError{
			method:    method,
			message:   rrh.GetErrorMsg(),
			code:      int(rrh.GetErrorDetail()),
			exception: rrh.GetExceptionClassName(),
		}
	}

	return nil
}

**Comment by kangyanf2008** [comment] 2019-04-28 11:40
Is there a solution?
My version is CDH6
	if err != nil {
		return err
	} else ### **if int32(rrh.GetCallId()) != c.currentRequestID** {
		return errors.New("unexpected sequence number")
	} else if rrh.GetStatus() != hadoop.RpcResponseHeaderProto_SUCCESS {
		return &NamenodeError{
			method:    method,
			message:   rrh.GetErrorMsg(),
			code:      int(rrh.GetErrorDetail()),
			exception: rrh.GetExceptionClassName(),
		}
	}

**Comment by colinmarc** [comment] 2019-11-24 00:10
Fixed in 1c841f7.

**Closed by colinmarc** 2019-11-24 00:10 UTC

**Comment by torubylist** [comment] 2020-06-12 08:14
still find the same issue after upgrade to 2.1.1.
core-site.xml
```
<property>
  <name>hadoop.security.authentication</name>
  <value>kerberos</value>
</property>
<property>
  <name>hadoop.security.authorization</name>
  <value>true</value>
</property>
```
klist

```
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: pdd-csiplugin/xxx@PROD.HELX.COM

Valid starting       Expires              Service principal
06/11/2020 22:15:25  06/12/2020 22:15:25  krbtgt/PROD.HELX.COM@PROD.HELX.COM
	renew until 06/18/2020 22:15:25

./hdfs ls hdfs://st1-htj-dwhd-1.prod.yiran.com:8020/
stat /: unexpected sequence number

```

**Comment by ZhangSIming-blyq** [comment] 2022-09-18 03:10
Have the error "unexpected sequence number" fixed? I met the same problem in some of the Windows WSL and Mac platform.
